export interface Equipment {
  id: string
  name: string
  category: string
  description: string
  dailyRate: number
  weeklyRate: number
  monthlyRate: number
  image: string
  specs: string[]
  available: boolean
  delivery: boolean
  featured: boolean
}

export const equipmentData: Equipment[] = [
  // SKID STEERS
  {
    id: "bobcat-s450",
    name: "Bobcat S450 Skid-Steer Loader",
    category: "Skid Steers",
    description:
      "Compact, agile skid-steer with 49 hp diesel engine. Ideal for tight spaces and mid-height lifting tasks in construction, landscaping, and agriculture.",
    dailyRate: 250,
    weeklyRate: 875,
    monthlyRate: 2500,
    image: "/bobcat-s450-skid-steer-yellow-loader.jpg",
    specs: ["49 HP Diesel", "1,370 lb Lift Capacity", "9.1 ft Lift Height", "Radius Lift Path"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-s250",
    name: "Bobcat S250 Skid-Steer Loader",
    category: "Skid Steers",
    description:
      "Powerful 75 hp vertical-lift skid steer built for heavy-duty work in construction, landscaping, and agriculture.",
    dailyRate: 275,
    weeklyRate: 950,
    monthlyRate: 2800,
    image: "/bobcat-s250-skid-steer-loader-construction.jpg",
    specs: ["75 HP", "2,500 lb Lift Capacity", "10.5 ft Lift Height", "Vertical Lift"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-s62",
    name: "Bobcat S62 Skid-Steer Loader",
    category: "Skid Steers",
    description:
      "Compact 68 hp radial-lift skid steer from Bobcat's R-Series. No DPF for lower maintenance, strong cast-steel arms, spacious sealed cab.",
    dailyRate: 265,
    weeklyRate: 925,
    monthlyRate: 2700,
    image: "/bobcat-s62-r-series-skid-steer.jpg",
    specs: ["68 HP", "No DPF", "R-Series", "Sealed Cab"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-s64",
    name: "Bobcat S64 Skid-Steer Loader",
    category: "Skid Steers",
    description:
      "68 hp radial-lift loader from Bobcat's R-Series. Built for power, comfort, and versatility with smooth ride and sealed cab.",
    dailyRate: 265,
    weeklyRate: 925,
    monthlyRate: 2700,
    image: "/bobcat-s64-skid-steer-r-series.jpg",
    specs: ["68 HP", "No DPF", "Smooth Ride", "R-Series"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-t450",
    name: "Bobcat T450 Compact Track Loader",
    category: "Skid Steers",
    description:
      "56-inch wide compact track loader designed for versatility and efficiency in tight workspaces with enhanced traction and stability.",
    dailyRate: 285,
    weeklyRate: 1000,
    monthlyRate: 2900,
    image: "/bobcat-t450-compact-track-loader.jpg",
    specs: ['56" Width', "Track Loader", "Enhanced Traction", "Tight Spaces"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-t550",
    name: "Bobcat T550 Compact Track Loader",
    category: "Skid Steers",
    description:
      "56-inch wide track loader ideal for landscaping, construction, and agriculture including grading, sod removal, tree planting, and material handling.",
    dailyRate: 295,
    weeklyRate: 1025,
    monthlyRate: 3000,
    image: "/bobcat-t550-compact-track-loader.jpg",
    specs: ['56" Width', "Track Loader", "Versatile", "Material Handling"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-t62",
    name: "Bobcat T62 Compact Track Loader",
    category: "Skid Steers",
    description:
      "Powerful R-Series compact track loader for digging, lifting, grading, and material handling with strong hydraulic performance.",
    dailyRate: 285,
    weeklyRate: 1000,
    monthlyRate: 2900,
    image: "/bobcat-t62-r-series-track-loader.jpg",
    specs: ["R-Series", "Strong Hydraulics", "Improved Comfort", "Daily Use Ready"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-t64",
    name: "Bobcat T64 Compact Track Loader",
    category: "Skid Steers",
    description:
      "Mid-frame vertical-lift compact track loader with 68 HP turbocharged Tier 4-compliant engine. No DPF minimizes maintenance and operating costs.",
    dailyRate: 295,
    weeklyRate: 1025,
    monthlyRate: 3000,
    image: "/bobcat-t64-vertical-lift-track-loader.jpg",
    specs: ["68 HP Turbo", "Vertical Lift", "No DPF", "Tier 4 Compliant"],
    available: true,
    delivery: true,
    featured: false,
  },

  // MINI SKID STEERS
  {
    id: "ditch-witch-sk800",
    name: "Ditch Witch SK800 Mini Skid Steer",
    category: "Mini Skid Steers",
    description:
      "Compact stand-on mini skid steer designed for versatility and durability. Built for heavy-duty operations in landscaping, utilities, and underground construction.",
    dailyRate: 195,
    weeklyRate: 680,
    monthlyRate: 1950,
    image: "/ditch-witch-sk800-mini-skid-steer-orange.jpg",
    specs: ["Stand-On Design", "Compact Size", "Heavy-Duty", "Underground Construction"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "ditch-witch-sk900",
    name: "Ditch Witch SK900 Mini Skid Steer",
    category: "Mini Skid Steers",
    description:
      "Compact stand-on mini skid steer for heavy-duty tasks with High-Drive Track System for enhanced stability, traction, and longevity.",
    dailyRate: 215,
    weeklyRate: 750,
    monthlyRate: 2150,
    image: "/ditch-witch-sk900-mini-skid-steer.jpg",
    specs: ["High-Drive Track System", "Smart Touch Control", "Enhanced Stability", "Bolt-On Sprockets"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "toro-tx1000",
    name: "Toro TX1000 Mini Skid Steer",
    category: "Mini Skid Steers",
    description:
      "Compact track-driven mini skid steer with vertical-lift loader arms for excellent reach and lift height. Fits through standard 36-inch gates.",
    dailyRate: 185,
    weeklyRate: 650,
    monthlyRate: 1850,
    image: "/toro-tx1000-mini-skid-steer.jpg",
    specs: ["Vertical-Lift Arms", 'Fits 36" Gates', "Track-Driven", "High Maneuverability"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-mt100",
    name: "Bobcat MT100 Mini Track Loader",
    category: "Mini Skid Steers",
    description:
      "Compact track-driven mini track loader designed for versatility and efficiency in tight spaces. Ideal for trenching, backfilling, and material handling.",
    dailyRate: 175,
    weeklyRate: 610,
    monthlyRate: 1750,
    image: "/bobcat-mt100-mini-track-loader.jpg",
    specs: ["Compact Design", "Track-Driven", "Tight Spaces", "Material Handling"],
    available: true,
    delivery: true,
    featured: false,
  },

  // MINI EXCAVATORS
  {
    id: "bobcat-e10",
    name: "Bobcat E10 Mini Excavator",
    category: "Mini Excavators",
    description:
      "Compact mini excavator designed for tight spaces with zero tail swing and retractable undercarriage. 10.2 hp diesel engine for reliable performance.",
    dailyRate: 195,
    weeklyRate: 680,
    monthlyRate: 1950,
    image: "/bobcat-e10-mini-excavator-compact.jpg",
    specs: ["10.2 HP Diesel", "Zero Tail Swing", "Retractable Undercarriage", "Tight Spaces"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e20",
    name: "Bobcat E20 Mini Excavator",
    category: "Mini Excavators",
    description:
      "Compact zero-tail-swing mini excavator with retractable undercarriage. 8.5 ft digging depth and 14 ft reach ideal for tight spaces.",
    dailyRate: 225,
    weeklyRate: 790,
    monthlyRate: 2250,
    image: "/bobcat-e20-mini-excavator.jpg",
    specs: ["Zero Tail Swing", "8.5 ft Dig Depth", "14 ft Reach", "Retractable Undercarriage"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e26",
    name: "Bobcat E26 Compact Excavator",
    category: "Mini Excavators",
    description:
      "Versatile R-Series compact excavator with minimal tail swing. Features improved visibility, Blade Float Function, and Auto Idle fuel savings.",
    dailyRate: 245,
    weeklyRate: 860,
    monthlyRate: 2450,
    image: "/bobcat-e26-r-series-excavator.jpg",
    specs: ["R-Series", "Minimal Tail Swing", "Blade Float Function", "Auto Idle"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e35",
    name: "Bobcat E35 Compact Excavator",
    category: "Mini Excavators",
    description:
      "Best-selling zero-tail-swing compact excavator with proven performance. Low-effort joysticks, in-track swing frame, and dual-flange roller system.",
    dailyRate: 275,
    weeklyRate: 960,
    monthlyRate: 2750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Zero Tail Swing", "Low-Effort Joysticks", "In-Track Swing Frame", "Best Seller"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-e42",
    name: "Bobcat E42 Compact Excavator",
    category: "Mini Excavators",
    description:
      "Versatile R2-Series compact excavator for confined spaces. Spacious cab with ergonomic controls, smooth hydraulics, and compatible with many attachments.",
    dailyRate: 295,
    weeklyRate: 1030,
    monthlyRate: 2950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["R2-Series", "Spacious Cab", "Ergonomic Controls", "Attachment Compatible"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e50",
    name: "Bobcat E50 Compact Excavator",
    category: "Mini Excavators",
    description:
      "R2-Series compact excavator with enhanced hydraulics featuring load-sensing pump and closed-center valve system for improved control.",
    dailyRate: 325,
    weeklyRate: 1140,
    monthlyRate: 3250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["R2-Series", "Load-Sensing Hydraulics", "Minimal Tail Swing", "Optional AC"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e88",
    name: "Bobcat E88 Compact Excavator",
    category: "Mini Excavators",
    description:
      "Conventional tail-swing R2-Series excavator for demanding tasks. Up to 14% more over-the-side lift capacity with advanced operator comfort features.",
    dailyRate: 395,
    weeklyRate: 1380,
    monthlyRate: 3950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["R2-Series", "14% More Lift Capacity", '7" Touchscreen', "Heavy-Duty"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "cat-308-cr",
    name: "Cat 308 CR Mini Excavator",
    category: "Mini Excavators",
    description:
      "Versatile Next Generation mini hydraulic excavator with Stick Steer Travel Mode and advanced load-sensing hydraulics delivering up to 44.2 gal/min flow.",
    dailyRate: 350,
    weeklyRate: 1225,
    monthlyRate: 3500,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Next Generation", "Stick Steer Mode", "44.2 gal/min Flow", "High Performance"],
    available: true,
    delivery: true,
    featured: true,
  },

  // COMPACTION EQUIPMENT
  {
    id: "ar14h-roller",
    name: "AR14H Vibratory Roller",
    category: "Compaction",
    description:
      '35.6" smooth drum vibratory roller with Honda GX630 engine. Compact 1-ton class with exceptional compaction performance on asphalt and granular soils.',
    dailyRate: 185,
    weeklyRate: 650,
    monthlyRate: 1850,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['35.6" Drum', "Honda GX630", "1-Ton Class", "Asphalt & Soil"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "mtx60hd-rammer",
    name: "MultiQuip MTX60HD Jumping Jack",
    category: "Compaction",
    description:
      "4-cycle rammer with Honda GX100 engine delivering 3,060 lb impact force. Ideal for confined area compaction with integrated tachometer/hour meter.",
    dailyRate: 65,
    weeklyRate: 230,
    monthlyRate: 650,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Honda GX100", "3,060 lb Impact", '10.4" Shoe', "EPA Compliant"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "mtx70hd-rammer",
    name: "MultiQuip MTX70HD Jumping Jack",
    category: "Compaction",
    description:
      "Most popular selling rammer with 3,350 lb impact force. Middle-weight compactor exceptionally well balanced for confined area compaction.",
    dailyRate: 70,
    weeklyRate: 245,
    monthlyRate: 700,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Honda GX100", "3,350 lb Impact", '11.2" Shoe', "Best Seller"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "rammax-rx1575",
    name: "Rammax RX1575 Trench Compactor",
    category: "Compaction",
    description:
      'Articulating trench roller with infrared remote control. 24/33" wide drums powered by 20HP Yanmar engine for reliable trench compaction.',
    dailyRate: 225,
    weeklyRate: 790,
    monthlyRate: 2250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Infrared Remote", '24/33" Drums', "20HP Yanmar", "Articulating"],
    available: true,
    delivery: true,
    featured: false,
  },

  // AIR COMPRESSORS & TOOLS
  {
    id: "airman-185",
    name: "AIRMAN 185 Air Compressor",
    category: "Air Compressors",
    description:
      "Tow-behind air compressor delivering 185 CFM @ 100 PSI. Manufactured to highest quality standards with industry's best return on investment.",
    dailyRate: 145,
    weeklyRate: 510,
    monthlyRate: 1450,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["185 CFM", "100 PSI", "24 Gal Fuel Tank", "Towable"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "sullair-375",
    name: "Sullair 375 Air Compressor",
    category: "Air Compressors",
    description:
      "Portable air compressor ready for variety of jobsite applications with air pressures up to 200 psi. Compact design with easy pressure change.",
    dailyRate: 195,
    weeklyRate: 680,
    monthlyRate: 1950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["375 CFM", "Up to 200 PSI", "Compact Design", "Extended Runtime"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "air-jackhammer-90",
    name: "90 lb Air Jack Hammer",
    category: "Air Compressors",
    description:
      "Sullair air-powered breaker hammer for variety of demolition applications. Steel tools available: chisels, points, spades, bush heads.",
    dailyRate: 55,
    weeklyRate: 195,
    monthlyRate: 550,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["90 lb", "Air-Powered", "Demolition", "Multiple Bits"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "chipping-hammer",
    name: "20 lb Chipping Hammer",
    category: "Air Compressors",
    description:
      "Designed for horizontal and overhead demolition with up to 1800 BPM. Variable speed throttle for improved control with rotatable exhaust deflector.",
    dailyRate: 35,
    weeklyRate: 125,
    monthlyRate: 350,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["20 lb", "1800 BPM", "Variable Speed", "D-Handle Design"],
    available: true,
    delivery: false,
    featured: false,
  },

  // SAWS
  {
    id: "husqvarna-k770",
    name: "Husqvarna K770 Power Cutter",
    category: "Saws",
    description:
      'Lightweight, high-performance 14" gas-powered saw with 5" cutting depth. SmartTension for optimal belt tension, low vibration and easy starts.',
    dailyRate: 75,
    weeklyRate: 265,
    monthlyRate: 750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['14" Blade', '5" Cut Depth', "SmartTension", "Low Vibration"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "husqvarna-k4000",
    name: "Husqvarna K4000 Electric Power Cutter",
    category: "Saws",
    description:
      'Electric power cutter with 14" dual-blade system for deep cuts up to 16" from one side. Zero emissions, ideal for indoor or precision work.',
    dailyRate: 95,
    weeklyRate: 335,
    monthlyRate: 950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['14" Dual-Blade', '16" Cut Depth', "Electric", "Zero Emissions"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "cx3-walk-behind-saw",
    name: "CX-3 Walk-Behind Concrete Saw",
    category: "Saws",
    description:
      'Compact 14" walk-behind saw for small to mid-size jobs. Lightweight aluminum frame, dual-side water delivery, folding handle for easy transport.',
    dailyRate: 125,
    weeklyRate: 440,
    monthlyRate: 1250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['14" Blade', "Wet or Dry Cutting", "Folding Handle", "Aluminum Frame"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "soff-cut-150",
    name: "Husqvarna Soff-Cut 150 Early Entry Saw",
    category: "Saws",
    description:
      'Lightweight gas-powered early entry saw for residential and light commercial use. 4.3 hp engine, 6" blade capacity, low-dust cutting.',
    dailyRate: 145,
    weeklyRate: 510,
    monthlyRate: 1450,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["4.3 HP", '6" Blade', "Early Entry", "Low-Dust"],
    available: true,
    delivery: true,
    featured: false,
  },

  // CONCRETE EQUIPMENT
  {
    id: "whiteman-wbh16f-buggy",
    name: "Whiteman WBH-16F Concrete Buggy",
    category: "Concrete",
    description:
      "16 cu. ft. gas-powered buggy with Honda GX390 engine. Foam-filled tires and hydrostatic drive for smooth control on tough job sites.",
    dailyRate: 175,
    weeklyRate: 615,
    monthlyRate: 1750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["16 cu ft", "Honda GX390", "Foam-Filled Tires", "Hydrostatic Drive"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "ultra-buggy-2500ts",
    name: "Ultra Buggy 2500-TS Tracked Power Buggy",
    category: "Concrete",
    description:
      "16 cu. ft. tracked power buggy with 2,500 lb capacity and 180° swivel dump. Powered by 25 hp Kohler engine for rough terrain.",
    dailyRate: 225,
    weeklyRate: 790,
    monthlyRate: 2250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["16 cu ft", "2,500 lb Capacity", "180° Swivel Dump", "25 HP Kohler"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "whiteman-wm90plf-mixer",
    name: "Multiquip Whiteman WM90PLF Mortar Mixer",
    category: "Concrete",
    description:
      "9-cubic-foot mortar mixer with durable polyethylene drum. Powered by 9 HP MPower engine with EasyClean technology and manual dump system.",
    dailyRate: 95,
    weeklyRate: 335,
    monthlyRate: 950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["9 cu ft", "9 HP MPower", "EasyClean Tech", "Manual Dump"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "mc94s-concrete-mixer",
    name: "MC94S Concrete Mixer",
    category: "Concrete",
    description:
      "9 cf concrete mixer setting standard for quality and dependability. Heavy duty tubular steel frame with forklift pockets, multiple power options.",
    dailyRate: 85,
    weeklyRate: 300,
    monthlyRate: 850,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["9 cu ft", "Steel Frame", "Forklift Pockets", "Multiple Power Options"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "power-trowel-36",
    name: 'Multiquip 36" Power Trowel',
    category: "Concrete",
    description:
      "Walk-behind concrete finisher powered by reliable 4.8 HP Honda GX160. QuickPitch Handle for fast blade angle adjustments with friction clutch for safety.",
    dailyRate: 125,
    weeklyRate: 440,
    monthlyRate: 1250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['36" Diameter', "4.8 HP Honda", "QuickPitch Handle", "Friction Clutch"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "power-trowel-48",
    name: 'Multiquip 48" Power Trowel',
    category: "Concrete",
    description:
      'Heavy-duty walk-behind finisher powered by 13HP Honda GX390. 48" 4-blade design with variable speed (35-225 RPM) for precise finishing.',
    dailyRate: 165,
    weeklyRate: 580,
    monthlyRate: 1650,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['48" Diameter', "13 HP Honda", "35-225 RPM", "4-Blade Design"],
    available: true,
    delivery: true,
    featured: false,
  },

  // FLOOR & CARPET EQUIPMENT
  {
    id: "obs-18dc-sander",
    name: "American Sanders OBS-18DC Orbital Sander",
    category: "Floor & Carpet",
    description:
      'Random-orbital floor sander with dust control at 3,600 orbits per minute. Perfect for screen and recoat and fine finish sanding with 12" x 18" sanding area.',
    dailyRate: 95,
    weeklyRate: 335,
    monthlyRate: 950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['12" x 18" Area', "3,600 OPM", "1 HP Motor", "Dust Control"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "mk-101-tile-saw",
    name: "MK-101 Pro24 JCS Tile Saw",
    category: "Floor & Carpet",
    description:
      'Professional-grade wet tile saw with 1.5 HP motor and 24" rip cut capacity. Integrated stand with heavy-duty wheels for easy transport.',
    dailyRate: 75,
    weeklyRate: 265,
    monthlyRate: 750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["1.5 HP", '10" Blade', '24" Rip Cut', "With Stand"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "mk-212-tile-saw",
    name: "MK-212-4 Tile & Stone Saw",
    category: "Floor & Carpet",
    description:
      "Rugged portable tile saw with powerful 2 HP direct drive motor. Adjustable miter system for cuts at all angles from 45° to 90° with plunge cutting head.",
    dailyRate: 85,
    weeklyRate: 300,
    monthlyRate: 850,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["2 HP Motor", "45°-90° Miter", "Plunge Cutting", "Portable"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "floor-buffer",
    name: 'Clarke CFP Pro 20" Floor Buffer',
    category: "Floor & Carpet",
    description:
      "20-inch floor buffer for carpet and hard floor use. 1.5 HP motor with pad driver included. Also available: concrete grinder attachment.",
    dailyRate: 55,
    weeklyRate: 195,
    monthlyRate: 550,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['20" Pad', "1.5 HP", "109 lbs", "Pad Driver Included"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "floor-stripper",
    name: "Palmer PG/101-2 Floor Stripper",
    category: "Floor & Carpet",
    description:
      "Powerful electric floor stripper for removing tile, linoleum, and carpet. 2,000 SPM oscillating blade with safe, tool-free blade change system.",
    dailyRate: 125,
    weeklyRate: 440,
    monthlyRate: 1250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["2,000 SPM", "Electric", "Tool-Free Blade Change", "Fast Stripping"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "carpet-stretcher",
    name: "Crain 500 Power Stretcher",
    category: "Floor & Carpet",
    description:
      "Professional carpet power stretcher with push-button stretch lock and Auto-Lok tube. Includes 3 extension tubes, transfer tube, and carrying case.",
    dailyRate: 45,
    weeklyRate: 160,
    monthlyRate: 450,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Push-Button Lock", "Auto-Lok Tube", "3 Extensions", "Carrying Case"],
    available: true,
    delivery: false,
    featured: false,
  },

  // DUMP TRAILERS
  {
    id: "dump-trailer-14k",
    name: "14K Dump Trailer",
    category: "Dump Trailers",
    description:
      "Heavy-duty electric/hydraulic dump trailer for tough hauling. 14,000 lb GVWR with dual 7,000 lb axles and hydraulic scissor lift.",
    dailyRate: 125,
    weeklyRate: 440,
    monthlyRate: 1250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["14,000 lb GVWR", "~10,000 lb Payload", "Dual 7K Axles", "Hydraulic Scissor Lift"],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "dump-trailer-10k",
    name: "10K Dump Trailer",
    category: "Dump Trailers",
    description:
      'Heavy-duty utility dump trailer popular with contractors and landscapers. 10,000 lb GVWR with 26" steel sides and hydraulic scissor lift.',
    dailyRate: 95,
    weeklyRate: 335,
    monthlyRate: 950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["10,000 lb GVWR", "~6,700 lb Payload", "Dual 5K Axles", '26" Steel Sides'],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "dump-trailer-7k",
    name: "7K Dump Trailer",
    category: "Dump Trailers",
    description:
      "Compact electric/hydraulic dump trailer for hauling gravel, dirt, and debris. 7,000 lb GVWR with 12V battery and 110V charger.",
    dailyRate: 75,
    weeklyRate: 265,
    monthlyRate: 750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["7,000 lb GVWR", "Dual 3.5K Axles", "Electric/Hydraulic", "12V with Charger"],
    available: true,
    delivery: false,
    featured: false,
  },

  // TRAILERS
  {
    id: "flatbed-7x16",
    name: "7x16 Construction Flatbed Trailer",
    category: "Trailers",
    description: "Standard construction flatbed trailer for equipment and material transport.",
    dailyRate: 55,
    weeklyRate: 195,
    monthlyRate: 550,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["7' x 16'", "Flatbed", "Equipment Transport", "Ramp Gate"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "gooseneck-20k",
    name: "20K 5th Wheel Gooseneck Trailer",
    category: "Trailers",
    description: "Heavy-duty 5th wheel gooseneck trailer with 20,000 lb capacity for large equipment transport.",
    dailyRate: 125,
    weeklyRate: 440,
    monthlyRate: 1250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["20,000 lb Capacity", "5th Wheel", "Gooseneck", "Heavy Equipment"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "car-hauler",
    name: "Car Hauler Trailer",
    category: "Trailers",
    description: "Flatbed car hauler trailer for transporting vehicles safely.",
    dailyRate: 65,
    weeklyRate: 230,
    monthlyRate: 650,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Vehicle Transport", "Flatbed", "Tie-Down Points", "Ramps"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "tilt-deck-trailer",
    name: "Tilt Deck Trailer",
    category: "Trailers",
    description: "Easy load/unload trailer with tilting deck for equipment and vehicles.",
    dailyRate: 75,
    weeklyRate: 265,
    monthlyRate: 750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Tilting Deck", "Easy Load", "Equipment Transport", "No Ramps Needed"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "water-trailer-600",
    name: "600 Gallon Water Trailer",
    category: "Trailers",
    description: "Large capacity water trailer for job sites, dust control, and irrigation.",
    dailyRate: 85,
    weeklyRate: 300,
    monthlyRate: 850,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["600 Gallon", "Job Site Use", "Dust Control", "Towable"],
    available: true,
    delivery: false,
    featured: false,
  },

  // GENERATORS & WELDERS
  {
    id: "generator-2.5kw",
    name: "2.5 kW Portable Generator",
    category: "Generators & Welders",
    description: "Portable power for tools, lights, and appliances at job sites or during power outages.",
    dailyRate: 45,
    weeklyRate: 160,
    monthlyRate: 450,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["2,500 Watts", "Portable", "Gas Powered", "Multiple Outlets"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "generator-6kw",
    name: "6 kW Portable Generator",
    category: "Generators & Welders",
    description: "Medium-duty portable power for tools, lights, and appliances at job sites.",
    dailyRate: 75,
    weeklyRate: 265,
    monthlyRate: 750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["6,000 Watts", "Portable", "Gas Powered", "Job Site Ready"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "generator-25kw-towable",
    name: "25 kW Towable Generator (3 Phase)",
    category: "Generators & Welders",
    description:
      "Heavy-duty power source for industrial-grade tools and multiple systems on large job sites. 3 Phase, 240V.",
    dailyRate: 195,
    weeklyRate: 680,
    monthlyRate: 1950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["25,000 Watts", "3 Phase", "240V", "Towable"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "welder-250-miller",
    name: "Miller 250 Amp Welder w/ 10 kW Generator",
    category: "Generators & Welders",
    description:
      "Medium-duty welder that doubles as a generator. Perfect for field welding with built-in power supply.",
    dailyRate: 125,
    weeklyRate: 440,
    monthlyRate: 1250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["250 Amp", "10 kW Generator", "Dual Purpose", "Field Ready"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "welder-400",
    name: "400 Amp Welder w/ 14 kW Generator",
    category: "Generators & Welders",
    description:
      "High-capacity welder suitable for large-scale welding operations with powerful 14 kW generator included.",
    dailyRate: 165,
    weeklyRate: 580,
    monthlyRate: 1650,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["400 Amp", "14 kW Generator", "Heavy-Duty", "Large Scale"],
    available: true,
    delivery: true,
    featured: false,
  },

  // LANDSCAPING
  {
    id: "rototiller-front",
    name: "Front Tine Rototiller",
    category: "Landscaping",
    description: "Loosens and mixes soil in smaller, already cultivated areas for garden prep and landscaping.",
    dailyRate: 55,
    weeklyRate: 195,
    monthlyRate: 550,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Front Tine", "Gas Powered", "Cultivated Areas", "Garden Prep"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "rototiller-rear",
    name: "Rear Tine Rototiller",
    category: "Landscaping",
    description:
      "More powerful tiller for breaking new ground or hard-packed soil. Self-propelled for easier operation.",
    dailyRate: 85,
    weeklyRate: 300,
    monthlyRate: 850,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Rear Tine", "Self-Propelled", "New Ground", "Heavy-Duty"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "aerator",
    name: "Lawn Aerator",
    category: "Landscaping",
    description: "Punches holes into lawn soil to allow air, water, and nutrients to reach roots for healthier grass.",
    dailyRate: 65,
    weeklyRate: 230,
    monthlyRate: 650,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Core Aerator", "Self-Propelled", "Lawn Health", "Gas Powered"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "dethatcher",
    name: "Dethatcher Power Rake",
    category: "Landscaping",
    description: "Removes layers of dead grass and debris (thatch) from lawns to promote healthy growth.",
    dailyRate: 55,
    weeklyRate: 195,
    monthlyRate: 550,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Power Rake", "Thatch Removal", "Lawn Care", "Gas Powered"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "sod-cutter",
    name: "Sod Cutter",
    category: "Landscaping",
    description: "Cuts and removes sod (grass with roots and soil) for new landscaping or turf installation.",
    dailyRate: 95,
    weeklyRate: 335,
    monthlyRate: 950,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Sod Removal", "Self-Propelled", "Adjustable Depth", "Gas Powered"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "sod-roller",
    name: "Sod Roller",
    category: "Landscaping",
    description: "Flattens and compacts newly laid sod or soil after seeding or fertilizing.",
    dailyRate: 25,
    weeklyRate: 90,
    monthlyRate: 250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Fill with Water", "Lawn Prep", "Sod Installation", "Manual Push"],
    available: true,
    delivery: false,
    featured: false,
  },

  // SCAFFOLDING & LIFTS
  {
    id: "baker-scaffold",
    name: "Baker Scaffolding w/ Wheels",
    category: "Scaffolding & Ladders",
    description: 'Compact mobile scaffold for indoor tasks and tight spaces. 72"H x 60"L x 24"W with locking wheels.',
    dailyRate: 35,
    weeklyRate: 125,
    monthlyRate: 350,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['72" Height', '60" Length', '24" Width', "Locking Wheels"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "scaffold-5x5x7",
    name: "5' x 5' x 7' Scaffold Set",
    category: "Scaffolding & Ladders",
    description: "Standard modular scaffold set for exterior or multi-level work. Platforms sold separately.",
    dailyRate: 45,
    weeklyRate: 160,
    monthlyRate: 450,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["5' x 5' x 7'", "Modular", "Multi-Level", "Exterior Use"],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "scissor-lift",
    name: "Scissor Lift",
    category: "Scaffolding & Ladders",
    description: "Mechanized lift platform for safe vertical access. Various heights available.",
    dailyRate: 175,
    weeklyRate: 615,
    monthlyRate: 1750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Electric", "Indoor/Outdoor", "Multiple Heights", "Safe Access"],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "extension-ladder",
    name: "Extension Ladder",
    category: "Scaffolding & Ladders",
    description: "Adjustable height ladder for roof access or tall structures. Various lengths available.",
    dailyRate: 25,
    weeklyRate: 90,
    monthlyRate: 250,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Adjustable Height", "Aluminum", "Roof Access", "Various Lengths"],
    available: true,
    delivery: false,
    featured: false,
  },

  // WATER EQUIPMENT
  {
    id: "trash-pump-2",
    name: '2" Trash Pump',
    category: "Water Equipment",
    description: 'For pumping water with debris. Handles solids up to 1" in diameter.',
    dailyRate: 65,
    weeklyRate: 230,
    monthlyRate: 650,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['2" Discharge', "Gas Powered", "Debris Handling", "Portable"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "trash-pump-3",
    name: '3" Trash Pump',
    category: "Water Equipment",
    description: "High-volume trash pump for pumping water with debris. Handles larger solids and higher flow rates.",
    dailyRate: 85,
    weeklyRate: 300,
    monthlyRate: 850,
    image: "/placeholder.svg?height=300&width=400",
    specs: ['3" Discharge', "Gas Powered", "High Volume", "Heavy-Duty"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "submersible-pump",
    name: "MultiQuip Submersible Pump",
    category: "Water Equipment",
    description: "Submersible pump for water removal from flooded areas, excavations, and pools.",
    dailyRate: 55,
    weeklyRate: 195,
    monthlyRate: 550,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Submersible", "Electric", "Water Removal", "Various Sizes"],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "pressure-washer",
    name: "Pressure Washer",
    category: "Water Equipment",
    description: "High-pressure washer for cleaning surfaces, equipment, and buildings.",
    dailyRate: 75,
    weeklyRate: 265,
    monthlyRate: 750,
    image: "/placeholder.svg?height=300&width=400",
    specs: ["Gas Powered", "High Pressure", "Surface Cleaning", "Portable"],
    available: true,
    delivery: false,
    featured: false,
  },
]
