export interface Equipment {
  id: string
  name: string
  category: string
  description: string
  dailyRate: number
  weeklyRate: number
  monthlyRate: number
  image: string
  specs: string[]
  available: boolean
  delivery: boolean
  featured: boolean
}

export const equipmentData: Equipment[] = [
  // ==================== HEAVY EQUIPMENT ====================
  // Skid Steers (Wheeled)
  {
    id: "bobcat-s450",
    name: "Bobcat S450 Skid-Steer Loader",
    category: "Heavy Equipment",
    description: "A compact, agile skid-steer with a 49 hp diesel engine and 1,370 lb lift capacity. Ideal for tight spaces and mid-height lifting tasks in construction, landscaping, and agriculture.",
    dailyRate: 350,
    weeklyRate: 1400,
    monthlyRate: 4200,
    image: "/equipment/bobcat-s450-skid-steer.jpg",
    specs: [
      "Lift Capacity: 1,370 lbs",
      "Engine: 49 HP Diesel",
      "Operating Weight: 5,370 lbs",
      "Lift Height: 9.1 ft",
      "Radius Lift Path",
      "Compatible with Bobcat Attachments",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-s250",
    name: "Bobcat S250 Skid-Steer Loader",
    category: "Heavy Equipment",
    description: "A powerful, 75 hp vertical-lift skid steer built for heavy-duty work in construction, landscaping, and agriculture.",
    dailyRate: 295,
    weeklyRate: 1180,
    monthlyRate: 3540,
    image: "/equipment/bobcat-s250-skid-steer.jpg",
    specs: [
      "Lift Capacity: 2,500 lbs",
      "Engine: 75 HP",
      "Operating Weight: 7,674 lbs",
      "Lift Height: 10.5 ft (126.4 in)",
      "Vertical Lift Path",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-s62",
    name: "Bobcat S62 Skid-Steer Loader",
    category: "Heavy Equipment",
    description: "A compact, 68 hp radial-lift skid steer from Bobcat's R-Series—built for power, comfort, and durability. Ideal for tough jobs in tight spaces.",
    dailyRate: 245,
    weeklyRate: 980,
    monthlyRate: 2940,
    image: "/equipment/bobcat-s62-skid-steer.jpg",
    specs: [
      "Engine: 68 HP",
      "Radial Lift Path",
      "No DPF - Lower Maintenance",
      "Cast-Steel Arms",
      "Spacious, Sealed Cab",
      "R-Series Design",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-s64",
    name: "Bobcat S64 Skid-Steer Loader",
    category: "Heavy Equipment",
    description: "A 68 hp, radial-lift loader from Bobcat's R-Series—built for power, comfort, and versatility. Great for tight job sites.",
    dailyRate: 250,
    weeklyRate: 1000,
    monthlyRate: 3000,
    image: "/equipment/bobcat-s64-skid-steer.jpg",
    specs: [
      "Engine: 68 HP",
      "Radial Lift Path",
      "No DPF - Less Maintenance",
      "Smooth Ride & Sealed Cab",
      "Strong Steel Lift Arms",
      "R-Series Design",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // Skid Steers (Track)
  {
    id: "bobcat-t450",
    name: "Bobcat T450 Compact Track Loader",
    category: "Heavy Equipment",
    description: "The Bobcat T450 is a compact track loader designed for versatility and efficiency in tight workspaces. With a width of just 56 inches, it can maneuver in confined areas while delivering robust performance.",
    dailyRate: 375,
    weeklyRate: 1500,
    monthlyRate: 4500,
    image: "/equipment/bobcat-t450-track-loader.jpg",
    specs: [
      "Width: 56 inches",
      "Compact Design",
      "Superior Traction",
      "Versatile Performance",
      "Tight Workspace Capability",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-t550",
    name: "Bobcat T550 Compact Track Loader",
    category: "Heavy Equipment",
    description: "The Bobcat T550 is a compact track loader designed for versatility and efficiency in tight workspaces. With a width of just 56 inches, it can maneuver in confined areas while delivering robust performance. Ideal for landscaping (grading, sod removal, tree planting), construction (backfilling, trenching, material handling), and agriculture (moving hay bales, feed, and bulk materials).",
    dailyRate: 395,
    weeklyRate: 1580,
    monthlyRate: 4740,
    image: "/equipment/bobcat-t550-track-loader.jpg",
    specs: [
      "Width: 56 inches",
      "Landscaping Applications",
      "Construction Tasks",
      "Agriculture Use",
      "Material Handling",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-t62",
    name: "Bobcat T62 Compact Track Loader",
    category: "Heavy Equipment",
    description: "The Bobcat T62 is a powerful compact track loader built for digging, lifting, grading, and material handling in tough environments. Part of the R-Series, it offers strong hydraulic performance and improved comfort, making it ideal for daily use on construction sites, farms, and landscaping projects.",
    dailyRate: 265,
    weeklyRate: 1060,
    monthlyRate: 3180,
    image: "/equipment/bobcat-t62-track-loader.jpg",
    specs: [
      "R-Series Design",
      "Strong Hydraulic Performance",
      "Digging & Lifting",
      "Grading Capability",
      "Material Handling",
      "Improved Comfort",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-t64",
    name: "Bobcat T64 Compact Track Loader",
    category: "Heavy Equipment",
    description: "The Bobcat T64 is a mid-frame, vertical-lift compact track loader engineered for versatility and performance across a variety of applications. With a 68-horsepower, turbocharged, Tier 4-compliant engine that operates without a diesel particulate filter (DPF), the T64 minimizes maintenance downtime and operating costs.",
    dailyRate: 280,
    weeklyRate: 1120,
    monthlyRate: 3360,
    image: "/equipment/bobcat-t64-track-loader.jpg",
    specs: [
      "Engine: 68 HP Turbocharged",
      "Vertical Lift Path",
      "No DPF - Lower Maintenance",
      "Tier 4 Compliant",
      "Mid-Frame Design",
      "Versatile Performance",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // Mini Skid Steers
  {
    id: "ditch-witch-sk800",
    name: "Ditch Witch SK800 Mini Skid-Steer",
    category: "Heavy Equipment",
    description: "The Ditch Witch SK800 is a compact, stand-on mini skid steer designed for versatility and durability across various tasks, including landscaping, utilities, and underground construction. Built for heavy-duty operations, it offers a balance of power, maneuverability, and operator comfort.",
    dailyRate: 195,
    weeklyRate: 780,
    monthlyRate: 2340,
    image: "/equipment/ditch-witch-sk800.jpg",
    specs: [
      "Stand-On Design",
      "Versatile Applications",
      "Heavy-Duty Operations",
      "Landscaping & Utilities",
      "Operator Comfort",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "ditch-witch-sk900",
    name: "Ditch Witch SK900 Mini Skid-Steer",
    category: "Heavy Equipment",
    description: "The Ditch Witch SK900 is a compact stand-on mini skid steer designed for heavy-duty tasks in tight spaces, offering enhanced power, stability, and ease of maintenance.",
    dailyRate: 215,
    weeklyRate: 860,
    monthlyRate: 2580,
    image: "/equipment/ditch-witch-sk900.jpg",
    specs: [
      "High-Drive Track System",
      "Smart Touch™ Control System",
      "Stand-On Design",
      "Enhanced Stability & Traction",
      "Easy Maintenance",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "toro-tx1000",
    name: "Toro TX1000 Mini Skid-Steer",
    category: "Heavy Equipment",
    description: "The Toro TX1000 is a compact, track-driven mini skid steer designed for heavy-duty tasks in confined spaces. With a vertical-lift loader arm, it offers impressive reach and lifting capacity, making it ideal for landscaping, construction, and utility work.",
    dailyRate: 235,
    weeklyRate: 940,
    monthlyRate: 2820,
    image: "/equipment/toro-tx1000.jpg",
    specs: [
      "Vertical-Lift Loader Arms",
      "Compact Size & High Maneuverability",
      "Fits Through 36-inch Gates",
      "Track-Driven Design",
      "Heavy-Duty Performance",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-mt100",
    name: "Bobcat MT100 Mini Track Loader",
    category: "Heavy Equipment",
    description: "The Bobcat MT100 is a compact, track-driven mini track loader designed for versatility and efficiency in tight spaces. Ideal for tasks like trenching, backfilling, and material handling, it offers a balance of power and maneuverability.",
    dailyRate: 225,
    weeklyRate: 900,
    monthlyRate: 2700,
    image: "/equipment/bobcat-mt100.jpg",
    specs: [
      "Track-Driven Design",
      "Compact & Efficient",
      "Trenching & Backfilling",
      "Material Handling",
      "Tight Space Operation",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // Mini Excavators
  {
    id: "bobcat-e10",
    name: "Bobcat E10 Mini Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E10 is a compact mini excavator designed for tight spaces. With its zero tail swing and retractable undercarriage, it excels in maneuverability and stability.",
    dailyRate: 245,
    weeklyRate: 980,
    monthlyRate: 2940,
    image: "/equipment/bobcat-e10.jpg",
    specs: [
      "Retractable Undercarriage",
      "Zero Tail Swing",
      "Engine: 10.2 HP Diesel",
      "Narrow Access Capability",
      "Enhanced Maneuverability",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e20",
    name: "Bobcat E20 Mini Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E20 is a compact, zero-tail-swing mini excavator, ideal for tight spaces. It features a retractable undercarriage and enhanced digging capabilities.",
    dailyRate: 275,
    weeklyRate: 1100,
    monthlyRate: 3300,
    image: "/equipment/bobcat-e20.jpg",
    specs: [
      "Retractable Undercarriage",
      "Zero Tail Swing",
      "Digging Depth: 8.5 ft",
      "Reach: 14 ft",
      "Confined Space Access",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-e26",
    name: "Bobcat E26 Mini Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E26 is a versatile, compact (mini) excavator designed for work in tight spaces, making it ideal for landscaping, utilities, and light construction. Part of Bobcat's R-Series, it combines powerful performance with operator comfort and a minimal tail swing design.",
    dailyRate: 295,
    weeklyRate: 1180,
    monthlyRate: 3540,
    image: "/equipment/bobcat-e26.jpg",
    specs: [
      "Minimal Tail Swing",
      "R-Series Cab - Improved Visibility",
      "Blade Float Function",
      "Auto Idle - Fuel Savings",
      "Landscaping & Utilities",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-e35",
    name: "Bobcat E35 Compact Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E35 is a best-selling, zero-tail-swing compact excavator built for tough jobsites. It offers proven performance, enhanced durability, and operator-focused features.",
    dailyRate: 325,
    weeklyRate: 1300,
    monthlyRate: 3900,
    image: "/equipment/bobcat-e35.jpg",
    specs: [
      "Low-Effort Joysticks",
      "In-Track Swing Frame",
      "Dual-Flange Roller System",
      "Simplified Maintenance",
      "Zero Tail Swing",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "bobcat-e42",
    name: "Bobcat E42 Compact Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E42 is a versatile compact excavator designed for efficient operation in confined spaces, making it ideal for landscaping, utilities, and light construction projects. As part of Bobcat's R2-Series, the E42 offers enhanced performance, comfort, and durability.",
    dailyRate: 345,
    weeklyRate: 1380,
    monthlyRate: 4140,
    image: "/equipment/bobcat-e42.jpg",
    specs: [
      "Spacious Cab - Ergonomic Controls",
      "Smooth, Precise Hydraulics",
      "Attachment Compatible",
      "Reinforced Durability",
      "R2-Series Design",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e50",
    name: "Bobcat E50 Compact Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E50 is a compact (mini) excavator designed for versatility and performance in confined spaces. As part of Bobcat's R2-Series, it offers enhanced features for various construction and landscaping tasks.",
    dailyRate: 365,
    weeklyRate: 1460,
    monthlyRate: 4380,
    image: "/equipment/bobcat-e50.jpg",
    specs: [
      "Minimal Tail Swing",
      "Enhanced Hydraulics - Load-Sensing Pump",
      "Spacious Cab - Improved Visibility",
      "Optional Air Conditioning",
      "R2-Series Design",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "bobcat-e88",
    name: "Bobcat E88 Compact Excavator",
    category: "Heavy Equipment",
    description: "The Bobcat E88 is a conventional tail-swing compact excavator in the R2-Series, designed for demanding construction, utility, and landscaping tasks. It offers enhanced lifting capacity, operator comfort, and advanced features for improved productivity.",
    dailyRate: 425,
    weeklyRate: 1700,
    monthlyRate: 5100,
    image: "/equipment/bobcat-e88.jpg",
    specs: [
      "High Lifting Capacity - 14% More",
      "Spacious Cab - Low-Effort Joysticks",
      "Optional Heated High-Back Seat",
      "7-inch Touchscreen Display",
      "R2-Series Design",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "cat-308-cr",
    name: "Cat 308 CR Mini Excavator",
    category: "Heavy Equipment",
    description: "The Caterpillar 308 CR is a versatile mini hydraulic excavator designed to deliver high performance in confined spaces. Part of Caterpillar's Next Generation series, it offers enhanced capabilities for a range of applications, including construction, landscaping, and utility work.",
    dailyRate: 395,
    weeklyRate: 1580,
    monthlyRate: 4740,
    image: "/equipment/cat-308-cr.jpg",
    specs: [
      "Stick Steer Travel Mode",
      "High-Performance Hydraulics",
      "Hydraulic Flow: 44.2 gal/min",
      "Joystick Steering Control",
      "Next Generation Series",
    ],
    available: true,
    delivery: true,
    featured: true,
  },

  // ==================== TRAILERS & TRANSPORT ====================
  // (Note: No trailer images were provided, but included for category completeness)

  // ==================== CONCRETE & COMPACTION ====================
  {
    id: "ar14h-vibratory-roller",
    name: "AR14H Vibratory Roller",
    category: "Concrete & Compaction",
    description: "The Compact, 1-ton class AR14-Series roller delivers exceptional compaction performance on asphalt and granular soils. A wise investment for demanding construction professionals looking for versatility and productivity.",
    dailyRate: 285,
    weeklyRate: 1140,
    monthlyRate: 3420,
    image: "/equipment/ar14h-vibratory-roller.jpg",
    specs: [
      "Drum Width: 35.6 inches",
      "Engine: Honda GX630",
      "1-Ton Class Roller",
      "Asphalt & Granular Soils",
      "Exceptional Compaction Performance",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "multiquip-mtx60hd",
    name: "MultiQuip MTX60HD Rammer (Jumping Jack)",
    category: "Concrete & Compaction",
    description: "For applications requiring even greater productivity, Multiquip's Mikasa MTX60HD 4-cycle rammer is the answer. Now with a redesigned fuel-tank that meets new EPA standards and features an integrated tachometer/hour meter.",
    dailyRate: 95,
    weeklyRate: 380,
    monthlyRate: 1140,
    image: "/equipment/multiquip-mtx60hd.jpg",
    specs: [
      "Engine: Honda GX100",
      "Impact Force: 3,060 lbs",
      "Shoe Size: 10.4 inches",
      "EPA Compliant Fuel Tank",
      "Integrated Tachometer/Hour Meter",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "multiquip-mtx70hd",
    name: "MultiQuip MTX70HD Rammer (Jumping Jack)",
    category: "Concrete & Compaction",
    description: "Multiquip's Mikasa MTX70HD is our most popular selling rammer – new and improved! This middle-weight compactor is ideal for confined area compaction and is exceptionally well balanced. Now with a redesigned fuel-tank that meets new EPA standards and features an integrated tachometer/hour meter.",
    dailyRate: 105,
    weeklyRate: 420,
    monthlyRate: 1260,
    image: "/equipment/multiquip-mtx70hd.jpg",
    specs: [
      "Engine: Honda GX100",
      "Impact Force: 3,350 lbs",
      "Shoe Size: 11.2 inches",
      "EPA Compliant Fuel Tank",
      "Integrated Tachometer/Hour Meter",
      "Exceptionally Well Balanced",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "rammax-rx1575",
    name: "Rammax RX1575 Trench Roller",
    category: "Concrete & Compaction",
    description: "The MQ Rammax RX1575 is an all new articulating trench roller designed to meet contractor expectations for performance and reliability. Experienced operators will appreciate the new design features that simplify operation and reduce downtime.",
    dailyRate: 155,
    weeklyRate: 620,
    monthlyRate: 1860,
    image: "/equipment/rammax-rx1575.jpg",
    specs: [
      "Infrared Remote Control",
      "Drum Width: 24/33 inches",
      "Engine: 20 HP Yanmar",
      "Articulating Design",
      "Simplified Operation",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "multiquip-mvc88vthw",
    name: "MultiQuip MVC88VTHW Plate Compactor",
    category: "Concrete & Compaction",
    description: "A top-selling compactor now improved with a single cast baseplate for added durability, built-in hour/tachometer, and an easier-to-use wheel kit. The anti-vibration handle boosts comfort and control on the job.",
    dailyRate: 75,
    weeklyRate: 300,
    monthlyRate: 900,
    image: "/equipment/multiquip-mvc88vthw.jpg",
    specs: [
      "Single Cast Baseplate",
      "Hour/Tachometer Included",
      "Anti-Vibration Handle",
      "Improved Wheel Kit",
      "Enhanced Durability",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "multiquip-mvc82vhw",
    name: "MultiQuip MVC82VHW Plate Compactor",
    category: "Concrete & Compaction",
    description: "The MVC82VHW is a reliable, single-direction plate compactor designed for compacting granular soils and asphalt. Equipped with a 5.5 HP Honda GX160 engine, it delivers 3,080 lbf of centrifugal force at 5,600 VPM. Features include a 17.7\" x 22.4\" steel base plate, anti-vibration handle, sealed belt cover, and a removable 11.5 qt water tank. Its compact design and durable construction make it ideal for small to medium-sized compaction projects.",
    dailyRate: 65,
    weeklyRate: 260,
    monthlyRate: 780,
    image: "/equipment/multiquip-mvc82vhw.jpg",
    specs: [
      "Centrifugal Force: 3,080 lbf",
      "Engine: Honda GX160 (5.5 HP)",
      "Plate Size: 17.7\" x 22.4\"",
      "Water Tank: 11.5 qt (Removable)",
      "Anti-Vibration Handle",
      "Sealed Belt Cover",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // Concrete Equipment
  {
    id: "whiteman-wbh-16f",
    name: "Whiteman WBH-16F",
    category: "Concrete & Compaction",
    description: "A 16 cu. ft. gas-powered buggy with a Honda GX390 engine and foam-filled tires. Features hydrostatic drive for smooth control and is ideal for hauling concrete, debris, and materials on tough job sites.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/whiteman-wbh-16f.jpg",
    specs: [
      "16 cu. ft. capacity",
      "Honda GX390 engine",
      "Foam-filled tires",
      "Hydrostatic drive",
      "Hauling concrete, debris, and materials",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "ultra-buggy-2500-ts",
    name: "Ultra Buggy® 2500-TS",
    category: "Concrete & Compaction",
    description: "A 16 cu. ft. tracked power buggy with a 2,500 lb. capacity and 180° swivel dump. Powered by a 25 hp Kohler engine, it's built for hauling and dumping materials on rough terrain with precision and control.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/ultra-buggy-2500-ts.jpg",
    specs: [
      "16 cu. ft. capacity",
      "2,500 lb. capacity",
      "180° swivel dump",
      "25 hp Kohler engine",
      "Tracked for rough terrain",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "multiquip-wm90plf",
    name: "Multiquip Whiteman WM90PLF",
    category: "Concrete & Compaction",
    description: "The Multiquip Whiteman WM90PLF is a 9-cubic-foot mortar mixer with a durable polyethylene drum, powered by a 9 HP MPower engine. It features EasyClean technology, a manual dump system, and a rugged steel frame for tough job site use.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/multiquip-whiteman-wm90plf.jpg",
    specs: [
      "9-cubic-foot mortar mixer",
      "Durable polyethylene drum",
      "9 HP MPower engine",
      "EasyClean technology",
      "Manual dump system & rugged steel frame",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "mc94s-concrete-mixer",
    name: "MC94S Series",
    category: "Concrete & Compaction",
    description: "9 cf Concrete, Electric & Gas Powered. This mixer sets the standard for quality and dependability. Heavy duty tubular steel frame with forklift pockets. Multiple power sources available. 9-cubic foot (248 liters) capacity. Easy loading and discharging of material.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/mc94s-series.jpg",
    specs: [
      "9-cubic foot (248 liters) capacity",
      "Electric & Gas Powered options",
      "Heavy duty tubular steel frame",
      "Forklift pockets",
      "Easy loading and discharging",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "magna-trap-dual-disc-grinder",
    name: "Magna-Trap® Dual-Disc 115V Electric Floor Grinder",
    category: "Concrete & Compaction",
    description: "The Magna-Trap® Dual-Disc 115V Electric Floor Grinder by EDCO is a 22\" surface prep tool ideal for grinding concrete, removing coatings, and smoothing surfaces. Powered by a 1.5 HP motor, it operates on standard 115V power.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/magna-trap-dual-disc-115v-electric-floor-grinder.jpg",
    specs: [
      "22\" EDCO surface prep tool",
      "1.5 HP motor - 115V power",
      "Dual-Disc Design - reduced operator fatigue",
      "Magna-Trap® Tooling System",
      "Grinding, coating removal, smoothing",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "magna-trap-single-disc-grinder",
    name: "Magna-Trap® Single-Disc Floor Grinder",
    category: "Concrete & Compaction",
    description: "The EDCO Magna-Trap® Single-Disc Floor Grinder is a compact, 115V surface prep tool ideal for smoothing concrete and removing coatings.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/magna-trap-single-disc-floor-grinder.jpg",
    specs: [
      "Compact EDCO grinder - 115V",
      "Magna-Trap® Tooling System",
      "Fast, wedge-free accessory changes",
      "Adjustable Height",
      "Precise grinding & extended tool life",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "multiquip-36-power-trowel",
    name: "Multiquip 36\" 4.8Hp Honda Quickpitch Power Trowel",
    category: "Concrete & Compaction",
    description: "The Multiquip 36\" QuickPitch Power Trowel is a walk-behind concrete finisher powered by a reliable 4.8 HP Honda GX160 engine. Ideal for mid-sized jobs, it delivers smooth, professional-grade surfaces.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/multiquip-36-4.8hp-honda-quickpitch-power-trowel.jpg",
    specs: [
      "36\" walk-behind concrete finisher",
      "4.8 HP Honda GX160 engine",
      "QuickPitch Handle - fast blade angle adjustments",
      "Friction Clutch - safety & quick stops",
      "Smooth, professional-grade surfaces",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "multiquip-48-power-trowel",
    name: "Multiquip 48\" 13HP Power Trowel",
    category: "Concrete & Compaction",
    description: "The Multiquip 48\" Power Trowel is a heavy-duty walk-behind finisher, ideal for large concrete surfaces. Powered by a 13HP Honda GX390 engine, it delivers high performance and smooth results.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/multiquip-48-13hp-power-trowel.jpg",
    specs: [
      "48\" heavy-duty walk-behind finisher",
      "13HP Honda GX390 engine",
      "48\" 4-blade design - wide coverage",
      "Variable speed (35–225 RPM)",
      "Precise finishing control for large surfaces",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "virginia-abrasives-core-drill",
    name: "Virginia Abrasives 3 Speed Hand Held Core Drill",
    category: "Concrete & Compaction",
    description: "The Virginia Abrasives 3-Speed Handheld Core Drill is a powerful 2 HP tool for drilling concrete and masonry, with speeds up to 3,450 RPM.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/virginia-abrasives-3-speed-hand-held-core-drill.jpg",
    specs: [
      "2 HP powerful handheld core drill",
      "3-speed motor for versatile drilling",
      "Speeds up to 3,450 RPM",
      "360° rotating handle",
      "Improved control and comfort",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "husqvarna-coring-rig",
    name: "HUSQVARNA Diamond Coring Rig",
    category: "Concrete & Compaction",
    description: "The Husqvarna DMS 240 Diamond Coring Rig is a powerful 2.9 HP drill for concrete and masonry, supporting up to 4\" core bits with variable speed control.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/husqvarna-diamond-coring-rig.jpg",
    specs: [
      "Husqvarna DMS 240",
      "2.9 HP powerful drill",
      "Up to 4\" core bits",
      "Variable speed (390–890 RPM)",
      "Adjustable angle up to 60°",
    ],
    available: true,
    delivery: true,
    featured: true,
  },

  // ==================== TRAILERS & TRANSPORT ====================
  {
    id: "14k-dump-trailer",
    name: "14 K Dump Trailer",
    category: "Trailers & Transport",
    description: "A heavy-duty electric/hydraulic dump trailer built for tough hauling—ideal for gravel, dirt, or debris.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/14-k-dump-trailer.jpg",
    specs: [
      "GVWR: 14,000 lbs",
      "Payload: ~9,200–10,000 lbs",
      "Axles: Dual 7,000 lb",
      "Hoist: Electric/hydraulic scissor lift",
      "Battery & Charger: 12V with 110V inverter",
    ],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "10k-dump-trailer",
    name: "10 K Dump Trailer",
    category: "Trailers & Transport",
    description: "A heavy-duty utility trailer designed for hauling materials like gravel, dirt, or debris. Popular with contractors and landscapers.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/10-k-dump-trailer.jpg",
    specs: [
      "GVWR: 10,000 lbs",
      "Payload: ~6,000–6,700 lbs",
      "Axles: Dual 5,000 lb",
      "Sides: 26\" steel",
      "Hoist: Hydraulic scissor lift",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "7k-dump-trailer",
    name: "7 K Dump Trailer",
    category: "Trailers & Transport",
    description: "A compact electric/hydraulic dump trailer for hauling materials like gravel, dirt, and debris.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/7-k-dump-trailer.jpg",
    specs: [
      "GVWR: 7,000 lbs",
      "Axles: Dual 3,500 lb",
      "Hoist: Electric/hydraulic",
      "Battery: 12V with 110V charger",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== WATER EQUIPMENT ====================
  {
    id: "600-gal-water-trailer",
    name: "600 Gallon Water Trailer",
    category: "General Tools",
    description: "Large capacity water trailer for dust control, concrete curing, and job site water supply. Features towable design with spray bar.",
    dailyRate: 95,
    weeklyRate: 380,
    monthlyRate: 1140,
    image: "/equipment/600-gal-water-trailer.jpg",
    specs: [
      "Capacity: 600 gallons",
      "Towable Design",
      "Spray Bar Included",
      "Honda Engine Pump",
      "Heavy-Duty Tank",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "trash-pump",
    name: "3\" Trash Pump",
    category: "General Tools",
    description: "Heavy-duty 3-inch trash pump for dewatering applications. Handles solids up to 1 inch, perfect for construction sites and flooding.",
    dailyRate: 85,
    weeklyRate: 340,
    monthlyRate: 1020,
    image: "/equipment/trashpump.jpg",
    specs: [
      "Port Size: 3 inches",
      "Engine: Honda GX200",
      "Flow Rate: 264 GPM",
      "Handles 1\" Solids",
      "Self-Priming",
    ],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "multiquip-sub-pump",
    name: "MultiQuip Submersible Pump",
    category: "General Tools",
    description: "Electric submersible pump for dewatering basements, excavations, and flooded areas. Automatic float switch for unattended operation.",
    dailyRate: 45,
    weeklyRate: 180,
    monthlyRate: 540,
    image: "/equipment/multiquip-sub-pump.jpg",
    specs: [
      "Motor: 115V Electric",
      "Flow Rate: 55 GPM",
      "Max Head: 25 feet",
      "Automatic Float Switch",
      "2\" Discharge",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== LANDSCAPING & GARDEN EQUIPMENT ====================
  // (No images provided for this category)

  // ==================== POWER TOOLS ====================
  {
    id: "airman-185-compressor",
    name: "AIRMAN 185 Air Compressor",
    category: "Power Tools",
    description: "AIRMAN air compressors are manufactured to the highest quality, consistently delivering the industry's best return on investment.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/airman-185-compressor.jpg",
    specs: [
      "185 CFM @ 100 PSI",
      "5.29 Tank Capacity",
      "24 Gal Fuel Tank Capacity",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "sullair-375-compressor",
    name: "Sullair 375 Compressor",
    category: "Power Tools",
    description: "Compact design with ample cooling and access for easy service. Easy pressure change with Variable Inlet Control. Extended runtime with low fuel consumption.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/sullair-375-compressor.jpg",
    specs: [
      "375 CFM at 100 psi working pressure",
      "100 Gallon Fuel Tank",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "wheeled-electric-compressor",
    name: "Wheeled Electric Air Compressor",
    category: "Power Tools",
    description: "Portable electric air compressor perfect for indoor use and jobsites with power access. Quiet operation with consistent air delivery.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/wheeled-electric-compressor.jpg",
    specs: [
      "1.5 HP Motor",
      "1755 RPM",
      "7.3 CFM @ 90 PSI",
      "9 Gallon Tank",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "puma-4-gallon-compressor",
    name: "Puma Industrial 4 Gallon Air Compressor",
    category: "Power Tools",
    description: "Compact portable compressor for light pneumatic tools. Perfect for nail guns, staplers, and small air tools in workshops or jobsites.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/puma-4-gallon-compressor.jpg",
    specs: [
      "9.1 cfm at 40 psi",
      "8.0 cfm at 90 psi",
      "135 psi Max working pressure",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "air-jack-hammer",
    name: "Air Jack Hammer - 90 & 60 lb",
    category: "Power Tools",
    description: "Sullair air compressors deliver reliable power with up to 1800 BPM to jackhammer concrete, asphalt, stone and other hard surfaces.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/air-jack-hammer.jpg",
    specs: [
      "Available in 90 lb & 60 lb",
      "Up to 1800 BPM",
      "Concrete & Asphalt Demolition",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "chipping-hammer",
    name: "Chipping Hammer - 20LB",
    category: "Power Tools",
    description: "A pneumatic chipping hammer offers high-powered air delivery at 1800 BPM. Features a variable speed throttle, designed to chip away at reinforced concrete, brick, tile, and hardened steel.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/chipping-hammer.jpg",
    specs: [
      "Weight: 20 lbs",
      "1800 BPM",
      "Variable Speed Throttle",
      "Reinforced Concrete & Hardened Steel",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "bostitch-n89c1-nail-gun",
    name: "Bostitch N89C-1 Pneumatic Nail Gun",
    category: "Power Tools",
    description: "Professional-grade framing nailer for wood construction. Drives nails from 2\" to 3-1/2\" with precision and power.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/bostitch-n89c1-nail-gun.jpg",
    specs: [
      "Push-button depth guide for consistent nail depth",
      "Large-capacity magazine holds over 200 framing nails",
      "2 1/2\" Ring Shank Nails",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "roundhead-framing-nailer",
    name: "RoundHead Framing Nailer",
    category: "Power Tools",
    description: "This nailer drives 3-1/2 in. framing nails to 1-1/2 inch concrete nails, with a magazine that holds 60-70 nails.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/roundhead-framing-nailer.jpg",
    specs: [
      "1-3/8\" Nails",
      "Drives up to 3-1/2 in. framing nails",
      "60-70 nail magazine capacity",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "hoses-fittings",
    name: "Air Hoses & Fittings",
    category: "Power Tools",
    description: "Professional-grade air hoses and quick-connect fittings for pneumatic tools. Available in 50' and 100' lengths.",
    dailyRate: 10,
    weeklyRate: 40,
    monthlyRate: 120,
    image: "/equipment/hoses-fittings.jpg",
    specs: [
      "Lengths: 50' or 100'",
      "Diameter: 3/4\" or 1\"",
      "Pressure Rating: 300 PSI",
      "Quick-Connect Fittings",
      "Heavy-Duty Rubber",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "drills",
    name: "Professional Cordless Drills",
    category: "Power Tools",
    description: "Heavy-duty cordless drills and drivers for construction applications. Includes batteries and charger.",
    dailyRate: 25,
    weeklyRate: 100,
    monthlyRate: 300,
    image: "/equipment/drills.jpg",
    specs: [
      "Voltage: 18V or 20V",
      "Chuck Size: 1/2\"",
      "Torque: 600+ in-lbs",
      "Includes: 2 Batteries",
      "Fast Charger Included",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "husqvarna-k770",
    name: "Husqvarna K 770",
    category: "Power Tools",
    description: "A lightweight, high-performance 14\" gas-powered saw with a 5\" cutting depth. Features SmartTension™ for optimal belt tension, low vibration, and easy starts—ideal for road work and masonry cutting.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/husqvarna-k-770.jpg",
    specs: [
      "14\" Gas-Powered Saw",
      "5\" Cutting Depth",
      "SmartTension™ System",
      "Low Vibration",
      "Easy Start",
    ],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "husqvarna-k4000",
    name: "Husqvarna K 4000",
    category: "Power Tools",
    description: "Electric power cutter with a 14\" dual-blade system, designed for deep cuts up to 16\" from one side. Ideal for flush cuts and openings without overcutting. Low noise and zero emissions—great for indoor or precision work.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/husqvarna-k-4000.jpg",
    specs: [
      "14\" Dual-Blade System",
      "16\" Deep Cuts from One Side",
      "Flush Cuts & Openings",
      "Low Noise",
      "Zero Emissions",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "cx3-walk-behind-saw",
    name: "CX-3® Walk-Behind Concrete Saw",
    category: "Power Tools",
    description: "A compact 14\" saw designed for small to mid-size jobs. Features a lightweight aluminum frame, dual-side water delivery, and folding handle for easy transport. Ideal for wet or dry cutting. Available with Concrete or Asphalt blade option.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/cx3-walk-behind-saw.jpg",
    specs: [
      "14\" Compact Saw",
      "Lightweight Aluminum Frame",
      "Dual-Side Water Delivery",
      "Folding Handle",
      "Wet or Dry Cutting",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "husqvarna-soff-cut-150",
    name: "Husqvarna Soff-Cut 150",
    category: "Power Tools",
    description: "A lightweight, gas-powered early entry saw for residential and light commercial use. Features a 4.3 hp engine, 6\" blade capacity, and low-dust, low-noise cutting—ideal for early concrete control joints.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/husqvarna-soff-cut-150.jpg",
    specs: [
      "4.3 HP Engine",
      "6\" Blade Capacity",
      "Low-Dust Cutting",
      "Low-Noise Operation",
      "Early Concrete Control Joints",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "concrete-blade",
    name: "Concrete Blade",
    category: "Power Tools",
    description: "Segmented with diamond teeth for cutting concrete and masonry.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/concrete-blade.jpg",
    specs: [
      "Segmented Design",
      "Diamond Teeth",
      "Concrete & Masonry Cutting",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "asphalt-blade",
    name: "Asphalt Blade",
    category: "Power Tools",
    description: "Continuous rim or hybrid for smooth cuts in asphalt and soft materials.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/asphalt-blade.jpg",
    specs: [
      "Continuous Rim or Hybrid",
      "Smooth Cuts",
      "Asphalt & Soft Materials",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "metal-blade",
    name: "Metal Blade",
    category: "Power Tools",
    description: "Carbide-tipped for cutting metal pipes, rebar, and steel.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/metal-blade.jpg",
    specs: [
      "Carbide-Tipped",
      "Metal Pipes",
      "Rebar & Steel Cutting",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== GENERATORS & WELDERS ====================
  // (No images provided for this category)

  // ==================== SCAFFOLDING, LADDERS & TEMP FENCE ====================
  // (No images provided for this category)

  // ==================== CARPET & FLOOR TOOLS ====================
  {
    id: "dewalt-hand-sander",
    name: "DEWALT Corded Hand Sander",
    category: "Carpet & Floor Tools",
    description: "The DWE6421 5 in. Single Speed Random Orbit Sander with hook & loop pad has a 3 Amp motor that delivers 12,000 OPM. The separate counterweight reduces vibration and along with the rubber overmold grip provides comfortable sanding. A shorter design allows users to get closer to the work surface and the one-handed locking dust bag attaches securely to the sander to aid in dust collection or the user can attach the sander directly to the DWV010 or DWV012 dust collectors.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/dewalt-hand-sander.jpg",
    specs: [
      "3 Amp motor - 12,000 OPM",
      "5 in. Random Orbit",
      "Hook & loop pad",
      "Reduced vibration design",
      "One-handed locking dust bag",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "bosch-roto-hammer",
    name: "Bosch Roto Hammer",
    category: "Carpet & Floor Tools",
    description: "20LB Roto Hammer with a 5\" Tile Bit. A powerful, corded tool built for heavy-duty concrete and masonry demolition. Delivers 6.1 ft.-lbs. of impact energy with SDS-Max bit system, Vario-Lock positioning, and hammer-only mode for efficient breaking and chipping.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/bosch-roto-hammer.jpg",
    specs: [
      "20LB Roto Hammer",
      "5\" Tile Bit",
      "6.1 ft.-lbs. impact energy",
      "SDS-Max bit system",
      "Vario-Lock positioning & hammer-only mode",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "palmer-pg101-floor-stripper",
    name: "Palmer PG/101-2 Floor Stripper",
    category: "Carpet & Floor Tools",
    description: "A powerful electric floor stripper designed to remove tile, linoleum, and carpet with ease. Features a 2,000 SPM oscillating blade and a safe, tool-free blade change system for fast, efficient stripping.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/palmer-pg101-floor-stripper.jpg",
    specs: [
      "Electric floor stripper",
      "2,000 SPM oscillating blade",
      "Tool-free blade change system",
      "Removes tile, linoleum, and carpet",
      "Fast, efficient stripping",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "american-sanders-obs18dc",
    name: "American Sanders OBS-18DC Orbital Sander w/Dust Control",
    category: "Carpet & Floor Tools",
    description: "The OBS-16DC utilizes random-orbital sanding action to efficiently remove the scratch patterns left behind from drum or rotary sanders. This will leave you with smooth, flat floor surface that is ready to refinish. The OBS-18DC is the fastest orbital sander on the market delivering an impressive 3,600 orbits per minute. This is the perfect machine for \"screen and recoat\" and fine finish sanding applications.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/american-sanders-obs18dc.jpg",
    specs: [
      "12\" x 18\" sanding area",
      "1 HP totally enclosed, dust free motor",
      "3,600 orbits per minute",
      "Convenient lifting handle",
      "9\" vacuum fan",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "sanding-paper",
    name: "Sanding Paper",
    category: "Carpet & Floor Tools",
    description: "Professional-grade sanding paper and discs for floor sanders. Available in various grits from extra coarse to fine finishing.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/sanding-paper.jpg",
    specs: [
      "20 Grit - Extra coarse (heavy material removal)",
      "36 Grit - Very coarse (removing adhesives/coatings)",
      "60 Grit - Coarse (initial smoothing)",
      "80 Grit - Medium (general-purpose sanding)",
      "100 Grit - Medium-fine (final prep before finishing)",
      "100 Grit Screen - Drywall/floor sanding",
      "150 Grit Screen - Final floor buffing",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "mk101-pro24-tile-saw",
    name: "MK-101 Pro24 JCS Tile Saw",
    category: "Carpet & Floor Tools",
    description: "The MK-101 Pro24 JCS is a professional-grade wet tile saw designed for precision and portability. It features a 1.5 HP motor, 10\" blade capacity, and a 24\" rip cut capacity, making it ideal for large-format tiles. The integrated stand with heavy-duty wheels allows for easy transport and setup, while the variable height cutting head enables plunge cuts. Its durable construction and high-volume water pump ensure efficient cooling and extended blade life.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/mk101-pro24-tile-saw.jpg",
    specs: [
      "1.5 HP motor",
      "10\" blade capacity",
      "24\" rip cut capacity",
      "Variable height cutting head - plunge cuts",
      "Integrated stand with heavy-duty wheels",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "crain-076-vinyl-roller",
    name: "Crain 076 100 lb. Vinyl Roller",
    category: "Carpet & Floor Tools",
    description: "Heavy-duty steel roller with zinc-plated, independently floating sections to prevent rust and adapt to uneven subfloors. Smooth, rounded rollers protect flooring, and recessed ends prevent wall scuffing.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/crain-076-vinyl-roller.jpg",
    specs: [
      "100 lb heavy-duty steel roller",
      "Zinc-plated floating sections",
      "Prevents rust, adapts to uneven subfloors",
      "Smooth, rounded rollers protect flooring",
      "Recessed ends prevent wall scuffing",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "k212-tile-stone-saw",
    name: "MK-212-4 Tile & Stone Saw",
    category: "Carpet & Floor Tools",
    description: "MK-212 Professional Tile and Stone Saws are built rugged and portable for use on any jobsite. The powerful 2 Hp direct drive motor is fully enclosed for greater protection. The adjustable built-in miter system allows cuts at all angles from 45° to 90°. The plunge cutting head has a pivoting blade guard for easy blade changes.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/k212-tile-stone-saw.jpg",
    specs: [
      "2 HP direct drive motor - fully enclosed",
      "10\" blade capacity",
      "Adjustable built-in miter system (45° to 90°)",
      "Plunge cutting head",
      "Pivoting blade guard for easy changes",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "crain-500-power-stretcher",
    name: "Crain 500 Power Stretcher",
    category: "Carpet & Floor Tools",
    description: "The Crain Power stretcher has the features that you would expect in a more expensive carpet stretcher. Comes complete with push-button stretch lock, Auto-Lok tube, 3 extension tube sections, 1 transfer tube section, folding tail block and carrying case with wheels.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/crain-500-power-stretcher.jpg",
    specs: [
      "Push-button stretch lock",
      "Auto-Lok tube",
      "3 extension tube sections + 1 transfer tube",
      "Folding tail block",
      "Carrying case with wheels",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "makinex-jackhammer-trolley",
    name: "Makinex Jackhammer Trolley",
    category: "Carpet & Floor Tools",
    description: "35LB Jack Hammer on an adjustable cart with 5\" Chisel Bit. Fast and easy removal of floor tiles, vinyl, and cork from concrete and wooden surfaces. Removes residue from tile beds and for breaking rocks, blocks, concrete, and sandstone. Ergonomic design minimizes vibration. Can be adjusted to 6 different positions, ranging from 20-80 degrees, to suit most demolition jobs.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/makinex-jackhammer-trolley.jpg",
    specs: [
      "35LB Jack Hammer on adjustable cart",
      "5\" Chisel Bit",
      "Adjustable 20-80 degrees (6 positions)",
      "Ergonomic design - minimizes vibration",
      "Tile, vinyl, cork, concrete removal",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "clarke-floor-buffer-20",
    name: "Clarke® CFP Pro® Floor Buffer (20\" Head) w/ Pad Holder",
    category: "Carpet & Floor Tools",
    description: "For carpet & hard floor use. Professional 20-inch floor buffer with pad driver included. 1.5 HP motor. Weighs 109 pounds.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/clarke-floor-buffer-20.jpg",
    specs: [
      "20 inch scrubbing path",
      "1.5 HP motor",
      "Pad driver included",
      "Weighs 109 pounds",
      "For carpet & hard floor use",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "buffer-pads",
    name: "Buffer Pads - 20\" Maintenance Pads",
    category: "Carpet & Floor Tools",
    description: "Professional 20-inch floor buffer pads in various colors for different applications. From stripping to polishing.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/buffer-pads.jpg",
    specs: [
      "White - Polish",
      "Red - Buffing",
      "Tan - Buffing",
      "Green - Scrubbing",
      "Black - Stripping",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "concrete-grinder-attachment",
    name: "Concrete Grinder Attachment",
    category: "Carpet & Floor Tools",
    description: "Concrete grinder attachment for smooth concrete finishing. Compatible with floor buffer for concrete surface preparation and polishing.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/concrete-grinder-attachment.jpg",
    specs: [
      "For smooth concrete finishing",
      "Compatible with 20\" floor buffer",
      "Surface preparation & polishing",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== WATER EQUIPMENT ====================
  // (No images provided for this category)

  // ==================== AUTOMOTIVE ====================
  {
    id: "bluebird-engine-hoist",
    name: "Bluebird® 1,500-lb. Engine Hoist",
    category: "Automotive",
    description: "Ideal for removing and installing vehicle engines and other various lifting jobs. Boom hook rotates 360-degrees and has a lift capacity of 1,500-lbs. Breaks down into 5-pieces and can fit into most vehicles. Weighs approximately 250-lbs and has a maximum height of just about 100-feet.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/bluebird-1500-lb-engine-hoist.jpg",
    specs: [
      "1,500-lb Lift Capacity",
      "360-Degree Rotating Boom Hook",
      "Breaks Down into 5 Pieces",
      "250-lb Weight",
      "100-ft Maximum Height",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "daytona-jack-stands",
    name: "Daytona Jack Stands",
    category: "Automotive",
    description: "These DAYTONA™ Heavy Duty Jack Stands safely support up to 6000 lb. for stable, dependable protection. They are constructed with heavy duty, solid steel body panels, and welded-in reinforcement braces for added strength and durability. These jack stands have an easy-to-use ratcheting system for quick height adjustments.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/daytona-jack-stands.jpg",
    specs: [
      "6000 lb Capacity",
      "11-3/8 in. to 16-7/8 in. lift height",
      "High-quality steel self-locking ratchet bar",
      "Double-locking mobility pin",
      "Includes two jack stands",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "transmission-jack",
    name: "Transmission Jack (1,000 lb)",
    category: "Automotive",
    description: "Heavy-duty transmission jack with 1,000 lb capacity. Features adjustable saddle and safety chains for secure transmission removal and installation.",
    dailyRate: 55,
    weeklyRate: 220,
    monthlyRate: 660,
    image: "/equipment/transmission-jack.jpg",
    specs: [
      "Capacity: 1,000 lbs",
      "Lift Range: 37\" - 71\"",
      "Adjustable Saddle",
      "Safety Chains",
      "360° Swivel Casters",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "pittsburgh-3-ton-floor-jack",
    name: "PITTSBURGH 3 Ton Floor Jack with RAPID PUMP",
    category: "Automotive",
    description: "This 3 Ton Car Jack gets vehicles almost two feet off the ground. A protective foam bumper on the jack handle protects vehicle surfaces from damage. Dual-piston RAPID PUMP® technology lifts most work loads in just 3-1/2 pumps.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/pittsburgh-3-ton-floor-jack.jpg",
    specs: [
      "3 Ton Capacity",
      "Lifts vehicles almost 2 feet",
      "RAPID PUMP® dual parallel-pump system",
      "Lifts in just 3-1/2 pumps",
      "Universal joint release for precise control",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== GENERAL TOOLS ====================

  // Material Handling Equipment
  {
    id: "pallet-jack",
    name: "Pallet Jack",
    category: "General Tools",
    description: "Used to lift and move pallets around warehouses or worksites. Manual hydraulic jack for efficient material handling.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Load Capacity: 5,500 lbs",
      "Fork Length: 48\"",
      "Fork Width: 27\"",
      "Hydraulic Lift System",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "dollies",
    name: "Dollies",
    category: "General Tools",
    description: "Wheeled platforms used to move heavy or bulky items easily. Essential for material transport on job sites.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Load Capacity: 1,000 lbs",
      "Heavy-Duty Wheels",
      "Non-Slip Surface",
      "Compact Storage",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // Demolition & Construction Tools
  {
    id: "wrecking-bars",
    name: "Wrecking Bars (Pry Bars)",
    category: "General Tools",
    description: "Used for demolition tasks such as pulling nails, prying boards, or lifting heavy items. Essential tool for demolition and construction work.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Heavy-Duty Steel Construction",
      "Multiple Sizes Available",
      "Nail Puller End",
      "Chisel Point",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "bolt-cutters",
    name: "Bolt Cutters",
    category: "General Tools",
    description: "Designed to cut through metal bolts, chains, padlocks, and wire mesh. High-leverage cutting power for tough materials.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Cutting Capacity: Up to 1/2\" bolts",
      "Hardened Steel Jaws",
      "Long Handles for Leverage",
      "Cuts Chain, Padlocks, Wire",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "rebar-bender",
    name: "Rebar Bender",
    category: "General Tools",
    description: "A tool used to bend reinforcing bars (rebar) to desired angles for construction use. Essential for concrete reinforcement work.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Bends up to #5 Rebar",
      "Adjustable Angle Settings",
      "Heavy-Duty Construction",
      "Portable Design",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // Finishing & Surface Prep
  {
    id: "wallpaper-steamer",
    name: "Wallpaper Steamer",
    category: "General Tools",
    description: "Used to loosen wallpaper adhesive for easy removal during renovations. Steam-powered for efficient wallpaper stripping.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Large Water Reservoir",
      "Quick Heat-Up Time",
      "Wide Steam Plate",
      "Easy-Grip Handle",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== GENERATORS & WELDERS ====================

  // Portable Generators
  {
    id: "generator-2-5kw",
    name: "2.5 kW Portable Generator",
    category: "Generators & Welders",
    description: "Provide portable power for tools, lights, and appliances at job sites or during power outages. Compact and fuel-efficient.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Output: 2.5 kW / 2,500 Watts",
      "Gas-Powered Engine",
      "Multiple Outlets",
      "Quiet Operation",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "generator-4-5kw",
    name: "4.5 kW Portable Generator",
    category: "Generators & Welders",
    description: "Provide portable power for tools, lights, and appliances at job sites or during power outages. Mid-size capacity for versatile use.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Output: 4.5 kW / 4,500 Watts",
      "Gas-Powered Engine",
      "Multiple Outlets",
      "Wheel Kit Included",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "generator-6kw",
    name: "6 kW Portable Generator",
    category: "Generators & Welders",
    description: "Provide portable power for tools, lights, and appliances at job sites or during power outages. High output for demanding applications.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Output: 6 kW / 6,000 Watts",
      "Gas-Powered Engine",
      "Electric Start",
      "Heavy-Duty Frame",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "generator-9-7kw",
    name: "9.7 kW Portable Generator",
    category: "Generators & Welders",
    description: "Provide portable power for tools, lights, and appliances at job sites or during power outages. Maximum portable power output.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Output: 9.7 kW / 9,700 Watts",
      "Gas-Powered Engine",
      "Electric Start",
      "Dual Voltage Output",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // Towable Generator
  {
    id: "generator-25kw-towable",
    name: "25 kW Towable Job Site Generator (3 Phase, 240V)",
    category: "Generators & Welders",
    description: "Heavy-duty power source for industrial-grade tools and multiple systems on large job sites. Three-phase power for professional applications.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Output: 25 kW",
      "3 Phase, 240V",
      "Towable Trailer Mounted",
      "Diesel Engine",
      "Sound-Attenuated Enclosure",
    ],
    available: true,
    delivery: true,
    featured: true,
  },

  // Welders
  {
    id: "miller-welder-250amp",
    name: "250 Amp Miller Welder w/ 10 kW Generator",
    category: "Generators & Welders",
    description: "For medium-duty welding jobs; doubles as a generator. Professional Miller quality with integrated power generation.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Welding Output: 250 Amps",
      "Generator Output: 10 kW",
      "Gas Engine Driven",
      "Stick & TIG Capable",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "welder-400amp",
    name: "400 Amp Welder w/ 14 kW Generator",
    category: "Generators & Welders",
    description: "High-capacity welder suitable for large-scale welding operations; includes powerful generator. Industrial-grade performance.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Welding Output: 400 Amps",
      "Generator Output: 14 kW",
      "Diesel Engine",
      "Multi-Process Capable",
    ],
    available: true,
    delivery: true,
    featured: true,
  },

  // Cutting Equipment
  {
    id: "oxy-acetylene-torch",
    name: "Torch with Oxygen & Acetylene",
    category: "Generators & Welders",
    description: "Used for cutting metal or welding using a combination of oxygen and acetylene gas. Complete torch kit with regulators.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Oxygen & Acetylene Tanks",
      "Regulators Included",
      "Cutting & Welding Tips",
      "Safety Equipment",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== SCAFFOLDING & LADDERS ====================

  // Scaffolding Systems
  {
    id: "baker-scaffolding",
    name: "Baker Scaffolding w/ Wheels (72\"H x 60\"L x 24\"W)",
    category: "Scaffolding & Ladders",
    description: "Compact, mobile scaffold for indoor tasks and tight spaces. Rolling scaffold with locking casters for safety.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Height: 72 inches",
      "Length: 60 inches",
      "Width: 24 inches",
      "Locking Casters",
      "Platform Height: 6 feet",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "scaffold-set-5x5x7",
    name: "5' x 5' x 7' Scaffold Sets",
    category: "Scaffolding & Ladders",
    description: "Standard modular sets for exterior or multi-level work. Heavy-duty steel construction for commercial applications.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "5' x 5' x 7' Frame",
      "Modular Design",
      "Heavy-Duty Steel",
      "Walk Boards Included",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "outdoor-scaffolding",
    name: "Outdoor Scaffolding",
    category: "Scaffolding & Ladders",
    description: "Heavy-duty scaffold for exterior construction or repairs. Weather-resistant and built for demanding outdoor work.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Heavy-Duty Construction",
      "Weather Resistant",
      "Multiple Height Options",
      "Safety Rails Included",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "scaffold-platforms",
    name: "Scaffolding Platforms",
    category: "Scaffolding & Ladders",
    description: "Walk surfaces for scaffolding systems. Aluminum or wood plank options available for various applications.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Various Lengths Available",
      "Aluminum or Wood",
      "Non-Slip Surface",
      "Load Rated",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // Ladders
  {
    id: "extension-ladders",
    name: "Extension Ladders",
    category: "Scaffolding & Ladders",
    description: "Adjustable height ladders for roof access or tall structures. Available in various heights for different applications.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Multiple Heights Available",
      "Fiberglass or Aluminum",
      "Type I or IA Rated",
      "Extension Lock System",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "a-frame-ladders",
    name: "A-Frame Ladders",
    category: "Scaffolding & Ladders",
    description: "Free-standing ladders for interior or short-height access. Stable platform for various tasks.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "4' to 12' Heights",
      "Self-Supporting",
      "Type I or IA Rated",
      "Tool Tray Included",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // Lifts & Towers
  {
    id: "scissor-lifts",
    name: "Scissor Lifts",
    category: "Scaffolding & Ladders",
    description: "Mechanized lift platforms for safe vertical access. Electric or gas-powered options for indoor and outdoor use.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Platform Heights: 19' to 32'",
      "Electric or Gas Models",
      "Rough Terrain Options",
      "500-800 lb Capacity",
    ],
    available: true,
    delivery: true,
    featured: true,
  },
  {
    id: "rolling-towers",
    name: "Rolling Towers",
    category: "Scaffolding & Ladders",
    description: "Movable scaffold towers for flexible height access. Mobile aluminum towers with locking casters.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Multiple Heights Available",
      "Aluminum Construction",
      "Locking Casters",
      "Quick Assembly",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // Temporary Barriers
  {
    id: "temporary-fencing",
    name: "Temporary Fencing (6' x 10')",
    category: "Scaffolding & Ladders",
    description: "For crowd control, safety zones, or site security. Chain-link panels with stands for easy installation.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Panel Size: 6' x 10'",
      "Chain-Link Construction",
      "Includes Stands",
      "Easy Installation",
    ],
    available: true,
    delivery: true,
    featured: false,
  },

  // ==================== LANDSCAPING & GARDEN ====================

  // Soil & Turf Preparation
  {
    id: "rototiller-front-tine",
    name: "Rototiller - Front Tine",
    category: "Landscaping & Garden",
    description: "Loosens and mixes soil in smaller, already cultivated areas. Lightweight and maneuverable for garden beds.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Tilling Width: 16-20 inches",
      "Gas Powered",
      "Adjustable Depth",
      "Forward Rotating Tines",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "rototiller-rear-tine",
    name: "Rototiller - Rear Tine",
    category: "Landscaping & Garden",
    description: "More powerful tiller for breaking new ground or hard-packed soil. Counter-rotating tines for tough conditions.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Tilling Width: 16-26 inches",
      "Gas Powered Engine",
      "Counter-Rotating Tines",
      "Heavy-Duty Construction",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "lawn-aerator",
    name: "Aerator",
    category: "Landscaping & Garden",
    description: "Punches holes into lawn soil to allow air, water, and nutrients to reach roots. Essential for lawn health and maintenance.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Core Aerator Type",
      "Gas or Manual Options",
      "18-24 inch Width",
      "Adjustable Depth",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "dethatcher-power-rake",
    name: "Dethatcher - Power Rake",
    category: "Landscaping & Garden",
    description: "Removes layers of dead grass and debris (thatch) from lawns to promote healthy growth. Gas-powered for efficient thatch removal.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Working Width: 18-20 inches",
      "Gas Powered",
      "Adjustable Blade Depth",
      "Spring Steel Tines",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "lawn-seeder",
    name: "Seeder",
    category: "Landscaping & Garden",
    description: "Distributes grass seed evenly over a lawn or soil surface. Broadcast or drop spreader options available.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Broadcast or Drop Type",
      "Adjustable Spread Rate",
      "Large Capacity Hopper",
      "Pneumatic Tires",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "sod-cutter",
    name: "Sod Cutter",
    category: "Landscaping & Garden",
    description: "Cuts and removes sod (grass with roots and soil) for new landscaping or turf installation. Gas-powered for professional results.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Cutting Width: 12-18 inches",
      "Gas Powered",
      "Adjustable Cut Depth",
      "Heavy-Duty Blade",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "sod-roller",
    name: "Sod Roller",
    category: "Landscaping & Garden",
    description: "Flattens and compacts newly laid sod or soil after seeding or fertilizing. Water-fillable for adjustable weight.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Roller Width: 18-24 inches",
      "Water-Fillable",
      "250-400 lb Capacity",
      "Tow-Behind Option",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "compost-roller",
    name: "Compost Roller",
    category: "Landscaping & Garden",
    description: "Turns and mixes compost materials to speed up decomposition. Rotating drum design for efficient composting.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 37-50 gallons",
      "Rotating Drum Design",
      "Easy-Turn Handle",
      "UV-Resistant Construction",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "turf-broom",
    name: "Turf Broom",
    category: "Landscaping & Garden",
    description: "Used to sweep and groom artificial turf or distribute infill evenly. Maintains synthetic grass appearance and performance.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Width: 36-48 inches",
      "Synthetic Bristles",
      "Tow-Behind Design",
      "Adjustable Bristle Pressure",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // Trimming & Clearing
  {
    id: "string-trimmer",
    name: "String Trimmer",
    category: "Landscaping & Garden",
    description: "Trims grass and weeds around edges, trees, and hard-to-reach areas. Gas-powered commercial-grade trimmer.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Gas Powered Engine",
      "Commercial Grade",
      "Straight or Curved Shaft",
      "Quick-Load Trimmer Head",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "hedge-trimmer",
    name: "Hedge Trimmer",
    category: "Landscaping & Garden",
    description: "Cuts and shapes hedges and bushes. Gas-powered with long cutting bar for professional landscaping.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Gas Powered",
      "24-30 inch Cutting Bar",
      "Double-Sided Blade",
      "Anti-Vibration System",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "weed-mower",
    name: "Weed Mower",
    category: "Landscaping & Garden",
    description: "Cuts down tall weeds and brush in overgrown areas. Heavy-duty walk-behind or tow-behind options.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Gas Powered",
      "Cutting Width: 20-26 inches",
      "Handles Thick Vegetation",
      "Self-Propelled",
    ],
    available: true,
    delivery: true,
    featured: false,
  },
  {
    id: "leaf-blower",
    name: "Leaf Blower",
    category: "Landscaping & Garden",
    description: "Blows leaves and debris into piles for easy cleanup. Commercial-grade backpack or handheld models.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Gas Powered",
      "Backpack or Handheld",
      "Variable Speed Control",
      "High CFM Output",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "backpack-sprayer",
    name: "Backpack Sprayer",
    category: "Landscaping & Garden",
    description: "Applies herbicides, pesticides, or fertilizers over large areas. Professional-grade pump sprayer with comfortable harness.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 4-5 gallons",
      "Pump or Battery Powered",
      "Adjustable Nozzle",
      "Padded Straps",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // General Use
  {
    id: "lawn-mower",
    name: "Lawn Mower",
    category: "Landscaping & Garden",
    description: "Cuts grass to an even height. Commercial walk-behind or riding mower options for various lawn sizes.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Gas Powered",
      "21-30 inch Deck",
      "Mulch or Bag Options",
      "Self-Propelled",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "wheelbarrow",
    name: "Wheelbarrow",
    category: "Landscaping & Garden",
    description: "Used to transport soil, mulch, tools, or other materials around a job site or garden. Heavy-duty contractor grade.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 6-10 cubic feet",
      "Steel or Poly Tray",
      "Pneumatic Tire",
      "Heavy-Duty Handles",
    ],
    available: true,
    delivery: false,
    featured: false,
  },

  // ==================== TRAILERS ====================

  {
    id: "flatbed-7x16",
    name: "Construction Flatbed Trailer 7x16",
    category: "Trailers & Transport",
    description: "Heavy-duty flatbed trailer for construction materials and equipment. 7 feet wide by 16 feet long.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Dimensions: 7' x 16'",
      "Tandem Axle",
      "Wood Deck",
      "Ramps Included",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "flatbed-7x20",
    name: "Construction Flatbed Trailer 7x20",
    category: "Trailers & Transport",
    description: "Heavy-duty flatbed trailer for construction materials and equipment. 7 feet wide by 20 feet long.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Dimensions: 7' x 20'",
      "Tandem Axle",
      "Wood Deck",
      "Ramps Included",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "flatbed-7x22",
    name: "Construction Flatbed Trailer 7x22",
    category: "Trailers & Transport",
    description: "Heavy-duty flatbed trailer for construction materials and equipment. 7 feet wide by 22 feet long.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Dimensions: 7' x 22'",
      "Tandem Axle",
      "Wood Deck",
      "Ramps Included",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "gooseneck-12k",
    name: "5th Wheel Gooseneck Trailer - 12K Capacity",
    category: "Trailers & Transport",
    description: "Heavy-duty gooseneck trailer with 12,000 lb capacity. Perfect for hauling heavy equipment and materials.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 12,000 lbs",
      "Gooseneck Hitch",
      "Tandem Axle",
      "Heavy-Duty Construction",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "gooseneck-20k",
    name: "5th Wheel Gooseneck Trailer - 20K Capacity",
    category: "Trailers & Transport",
    description: "Heavy-duty gooseneck trailer with 20,000 lb capacity. Maximum capacity for the heaviest loads.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 20,000 lbs",
      "Gooseneck Hitch",
      "Triple Axle",
      "Heavy-Duty Construction",
    ],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "car-tow-dolly",
    name: "Car/Tow Dolly",
    category: "Trailers & Transport",
    description: "For towing small cars with front wheels on the dolly. Compact and easy to maneuver.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 3,450 lbs",
      "Tow Bar Included",
      "Swivel Hitch",
      "Ratchet Straps",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "car-hauler",
    name: "Car Hauler",
    category: "Trailers & Transport",
    description: "For transporting cars on a full flatbed trailer. Drive-on design with ramps.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 7,000 lbs",
      "18-20 foot Deck",
      "Ramps Included",
      "Winch Mount",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "atv-trailer",
    name: "ATV Trailer",
    category: "Trailers & Transport",
    description: "For hauling ATVs, UTVs, and small equipment. Compact design with ramps.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 2,000-3,000 lbs",
      "5' x 10' Deck",
      "Fold-Down Ramp",
      "Mesh Sides",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "tilt-deck-trailer",
    name: "Tilt Deck Trailer",
    category: "Trailers & Transport",
    description: "Easy load/unload with tilting deck mechanism. Perfect for heavy equipment without ramps.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 14,000 lbs",
      "Hydraulic Tilt",
      "14-16 foot Deck",
      "Heavy-Duty Construction",
    ],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "utility-trailer",
    name: "Utility Trailer",
    category: "Trailers & Transport",
    description: "Versatile trailer for general hauling of materials, equipment, and supplies.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 2,990 lbs",
      "5' x 8' to 6' x 12'",
      "Mesh or Solid Sides",
      "Tailgate",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "dump-trailer-7k",
    name: "Dump Trailer - 7K Capacity",
    category: "Trailers & Transport",
    description: "Hydraulic dump trailer for easy unloading of materials. 7,000 lb capacity.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 7,000 lbs",
      "Hydraulic Lift",
      "6' x 12' Bed",
      "Steel Construction",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "dump-trailer-14k",
    name: "Dump Trailer - 14K Capacity",
    category: "Trailers & Transport",
    description: "Heavy-duty hydraulic dump trailer for easy unloading. 14,000 lb capacity.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 14,000 lbs",
      "Hydraulic Lift",
      "7' x 14' Bed",
      "Heavy-Duty Steel",
    ],
    available: true,
    delivery: false,
    featured: true,
  },
  {
    id: "horse-trailer",
    name: "Horse Enclosed Trailer",
    category: "Trailers & Transport",
    description: "For transporting horses safely and comfortably. Enclosed design with ventilation.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "2-3 Horse Capacity",
      "Enclosed with Windows",
      "Rubber Floor Mats",
      "Tack Storage",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "enclosed-trailer",
    name: "Enclosed Trailer",
    category: "Trailers & Transport",
    description: "Secured storage for goods and equipment during transport. Weather-protected cargo area.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "6' x 12' to 8.5' x 20'",
      "Rear Ramp Door",
      "Side Door Access",
      "Interior Tie-Downs",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
  {
    id: "water-trailer",
    name: "Water Trailer",
    category: "Trailers & Transport",
    description: "For water transport and dust control on job sites. Large capacity tank with pump system.",
    dailyRate: 0,
    weeklyRate: 0,
    monthlyRate: 0,
    image: "/equipment/placeholder.jpg",
    specs: [
      "Capacity: 500-1,000 gallons",
      "Spray Bar System",
      "Pump Included",
      "DOT Approved",
    ],
    available: true,
    delivery: false,
    featured: false,
  },
]
